services:
  app:
    build: .
    container_name: aury_app
    ports:
      - "8686:8686"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:8.0
    container_name: aury_mongodb
    ports:
      - "27033:27033"
    command: ["mongod", "--port", "27033"]
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: aury_db
    restart: unless-stopped

volumes:
  mongodb_data:
